/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Play2DothtmlRouteImport } from './routes/play2[.]html'
import { Route as PlayDotphpRouteImport } from './routes/play[.]php'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VidcloudSplatRouteImport } from './routes/vidcloud.$'
import { Route as S2cdnSplatRouteImport } from './routes/s2cdn.$'
import { Route as ApiBatchesDotjsonRouteImport } from './routes/api/batches[.]json'

const Play2DothtmlRoute = Play2DothtmlRouteImport.update({
  id: '/play2.html',
  path: '/play2.html',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDotphpRoute = PlayDotphpRouteImport.update({
  id: '/play.php',
  path: '/play.php',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VidcloudSplatRoute = VidcloudSplatRouteImport.update({
  id: '/vidcloud/$',
  path: '/vidcloud/$',
  getParentRoute: () => rootRouteImport,
} as any)
const S2cdnSplatRoute = S2cdnSplatRouteImport.update({
  id: '/s2cdn/$',
  path: '/s2cdn/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBatchesDotjsonRoute = ApiBatchesDotjsonRouteImport.update({
  id: '/api/batches.json',
  path: '/api/batches.json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/play.php': typeof PlayDotphpRoute
  '/play2.html': typeof Play2DothtmlRoute
  '/api/batches.json': typeof ApiBatchesDotjsonRoute
  '/s2cdn/$': typeof S2cdnSplatRoute
  '/vidcloud/$': typeof VidcloudSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/play.php': typeof PlayDotphpRoute
  '/play2.html': typeof Play2DothtmlRoute
  '/api/batches.json': typeof ApiBatchesDotjsonRoute
  '/s2cdn/$': typeof S2cdnSplatRoute
  '/vidcloud/$': typeof VidcloudSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/play.php': typeof PlayDotphpRoute
  '/play2.html': typeof Play2DothtmlRoute
  '/api/batches.json': typeof ApiBatchesDotjsonRoute
  '/s2cdn/$': typeof S2cdnSplatRoute
  '/vidcloud/$': typeof VidcloudSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/play.php'
    | '/play2.html'
    | '/api/batches.json'
    | '/s2cdn/$'
    | '/vidcloud/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/play.php'
    | '/play2.html'
    | '/api/batches.json'
    | '/s2cdn/$'
    | '/vidcloud/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/play.php'
    | '/play2.html'
    | '/api/batches.json'
    | '/s2cdn/$'
    | '/vidcloud/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRoute
  PlayDotphpRoute: typeof PlayDotphpRoute
  Play2DothtmlRoute: typeof Play2DothtmlRoute
  ApiBatchesDotjsonRoute: typeof ApiBatchesDotjsonRoute
  S2cdnSplatRoute: typeof S2cdnSplatRoute
  VidcloudSplatRoute: typeof VidcloudSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/play2.html': {
      id: '/play2.html'
      path: '/play2.html'
      fullPath: '/play2.html'
      preLoaderRoute: typeof Play2DothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play.php': {
      id: '/play.php'
      path: '/play.php'
      fullPath: '/play.php'
      preLoaderRoute: typeof PlayDotphpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vidcloud/$': {
      id: '/vidcloud/$'
      path: '/vidcloud/$'
      fullPath: '/vidcloud/$'
      preLoaderRoute: typeof VidcloudSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s2cdn/$': {
      id: '/s2cdn/$'
      path: '/s2cdn/$'
      fullPath: '/s2cdn/$'
      preLoaderRoute: typeof S2cdnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/batches.json': {
      id: '/api/batches.json'
      path: '/api/batches.json'
      fullPath: '/api/batches.json'
      preLoaderRoute: typeof ApiBatchesDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRoute,
  PlayDotphpRoute: PlayDotphpRoute,
  Play2DothtmlRoute: Play2DothtmlRoute,
  ApiBatchesDotjsonRoute: ApiBatchesDotjsonRoute,
  S2cdnSplatRoute: S2cdnSplatRoute,
  VidcloudSplatRoute: VidcloudSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
